import { actionRegistry } from './registry';
import { queryTimeEntriesAction } from './read/queryTimeEntries';
import { listCategoriesAction } from './read/listCategories';
import { listGoalsAction } from './read/listGoals';
import { searchMemosAction } from './read/searchMemos';
import { addEntryAction } from './write/addEntry';
import { updateEntryAction } from './write/updateEntry';
import { deleteEntryAction } from './write/deleteEntry';
import { mergeEntriesAction } from './write/mergeEntries';
import { splitEntryAction } from './write/splitEntry';
import { addGoalAction } from './write/addGoal';
import { updateGoalAction } from './write/updateGoal';
import { deleteGoalAction } from './write/deleteGoal';
import { findOverlapsAction } from './maintenance/findOverlaps';
import { findGapsAction } from './maintenance/findGaps';
import { findAnomaliesAction } from './maintenance/findAnomalies';
import { autoCategorizeAction } from './maintenance/autoCategorize';
import { batchUpdateAction } from './maintenance/batchUpdate';

actionRegistry.register(queryTimeEntriesAction);
actionRegistry.register(listCategoriesAction);
actionRegistry.register(listGoalsAction);
actionRegistry.register(searchMemosAction);
actionRegistry.register(addEntryAction);
actionRegistry.register(updateEntryAction);
actionRegistry.register(deleteEntryAction);
actionRegistry.register(mergeEntriesAction);
actionRegistry.register(splitEntryAction);
actionRegistry.register(addGoalAction);
actionRegistry.register(updateGoalAction);
actionRegistry.register(deleteGoalAction);
actionRegistry.register(findOverlapsAction);
actionRegistry.register(findGapsAction);
actionRegistry.register(findAnomaliesAction);
actionRegistry.register(autoCategorizeAction);
actionRegistry.register(batchUpdateAction);

export { actionRegistry } from './registry';
export type { ActionDefinition, ActionResult, ActionCategory, RiskLevel, ConfirmationCard, ConfirmationChange } from './types';
